distributable:
  url: https://github.com/containers/podman/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: containers/podman/releases/tags

platforms:
  - darwin
  #fixme: - linux once qemu is built

provides:
  - bin/podman
  - bin/podman-mac-helper

dependencies:
  qemu.org: '*'
  github.com/containers/gvisor-tap-vsock: '*'

build:
  dependencies:
    go.dev: ^1.18
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
  script: |
    sed -i.bak \
      '\#var defaultHelperBinariesDir#a\'$'\n\"$BINDIR/../../../github.com/containers/gvisor-tap-vsock/v0/bin\",'$'\n' \
      vendor/github.com/containers/common/pkg/config/config_darwin.go    

    make --jobs {{ hw.concurrency }} podman-remote
    make --jobs {{ hw.concurrency }} podman-mac-helper
    mkdir -p "{{ prefix }}"/bin
    mv bin/"{{ hw.platform }}"/* "{{ prefix }}"/bin
    ln -s podman "{{ prefix }}"/bin/podman-remote
  env:
    CGO_ENABLED: 1

test:
  script: |
    podman-remote -v | grep "podman-remote version {{ version }}"
    (podman info 2>&1 || true) | grep "Cannot connect to Podman."
    (podman machine init --image-path fake-testimage fake-testvm 2>&1 || true) | grep "Error: open fake-testimage: no such file or directory"

