distributable:
  url: https://www.libssh.org/files/{{ version.major }}.{{ version.minor }}/libssh-{{ version }}.tar.xz 
  strip-components: 1

versions:
  - 0.10.4

dependencies:
  openssl.org: ^1.1

build:
  dependencies:
    tea.xyz/gx/make: '*'
    cmake.org: ^3
  working-directory: build
  script: |
    cmake .. $ARGS
    make install
  env:
    ARGS:
      - -DBUILD_STATIC_LIB=ON
      - -DWITH_SYMBOL_VERSIONING=OFF
      - -DCMAKE_BUILD_TYPE=Release 
      - -DCMAKE_INSTALL_PREFIX={{prefix}}

test:
  dependencies:
    tea.xyz/gx/cc: '*'
  script: |
    mv $FIXTURE test.c
    gcc -lssh -o test
    ./test
  fixture: |
    #include <libssh/libssh.h>
    #include <stdlib.h>
    int main()
    {
      ssh_session my_ssh_session = ssh_new();
      if (my_ssh_session == NULL)
        exit(-1);
      ssh_free(my_ssh_session);
      return 0;
    }


