distributable:
   url: https://github.com/helm/helm/archive/refs/tags/v{{version}}.tar.gz
   strip-components: 1

versions:
  github: helm/helm/releases/tags

provides:
  - bin/helm

build:
  dependencies:
    go.dev: ^1.19
    tea.xyz/gx/make: '*'
  script: |
    make build
    mkdir -p "{{ prefix }}"/bin
    mv bin/helm "{{ prefix }}"/bin

test:
  script: |
    helm create foo
    test -d "foo/charts"
    helm version | grep "GitTreeState:\"clean\""
    helm version | grep "Version:\"{{version}}\""
